[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.73.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/fr-petition"
  to = "http://chng.it/4x7mXzjC" 
  status = 301

[[redirects]]
  from = "/twitch"
  to = "https://twitch.tv/cpcscc" 
  status = 301

[[redirects]]
  from = "/youtube"
  to = "https://www.youtube.com/channel/UCTbnfy8qfrI5zn9vwIMrFmA" 
  status = 301
